//! Sparkplug B protobuf types, generated by `prost-build` from
//! `vendor/sparkplug-b/sparkplug_b.proto`. The schema is a clean-room
//! reconstruction of the public Sparkplug B specification (no upstream `.proto`
//! source was copied); see the header comment in the `.proto` file for details.
//!
//! The schema declares `package marlinspike.sparkplug_b;`, which `prost-build`
//! writes to `$OUT_DIR/marlinspike.sparkplug_b.rs`.

include!(concat!(env!("OUT_DIR"), "/marlinspike.sparkplug_b.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use prost::Message;

    #[test]
    fn payload_encode_decode_roundtrip() {
        let p = Payload {
            timestamp: Some(1_700_000_000_000),
            seq: Some(7),
            ..Default::default()
        };
        let bytes = p.encode_to_vec();
        let decoded = Payload::decode(&bytes[..]).expect("decode");
        assert_eq!(decoded.timestamp, Some(1_700_000_000_000));
        assert_eq!(decoded.seq, Some(7));
        assert!(decoded.metrics.is_empty());
    }

    #[test]
    fn metric_with_double_value_roundtrip() {
        let m = payload::Metric {
            name: Some("BearingTemp".into()),
            alias: Some(42),
            datatype: Some(10), // DataType::Double per Sparkplug B spec
            value: Some(payload::metric::Value::DoubleValue(72.5)),
            ..Default::default()
        };
        let bytes = m.encode_to_vec();
        let decoded = payload::Metric::decode(&bytes[..]).expect("decode");
        assert_eq!(decoded.name.as_deref(), Some("BearingTemp"));
        assert_eq!(decoded.alias, Some(42));
        assert!(matches!(
            decoded.value,
            Some(payload::metric::Value::DoubleValue(v)) if (v - 72.5).abs() < 1e-9
        ));
    }

    #[test]
    fn payload_with_metric_roundtrip() {
        let p = Payload {
            timestamp: Some(1_700_000_000_000),
            seq: Some(1),
            metrics: vec![payload::Metric {
                name: Some("Tank1.Level".into()),
                alias: Some(1),
                datatype: Some(9), // Float
                value: Some(payload::metric::Value::FloatValue(3.14)),
                ..Default::default()
            }],
            ..Default::default()
        };
        let bytes = p.encode_to_vec();
        let decoded = Payload::decode(&bytes[..]).expect("decode");
        assert_eq!(decoded.metrics.len(), 1);
        assert_eq!(decoded.metrics[0].alias, Some(1));
    }
}
